// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrGmMTg27SbCCza3_-JVlD_TAvWXOHULs',
    appId: '1:912044780067:web:4b161c4d7390d373cadf96',
    messagingSenderId: '912044780067',
    projectId: 'meal-app-ngt',
    authDomain: 'meal-app-ngt.firebaseapp.com',
    storageBucket: 'meal-app-ngt.firebasestorage.app',
    measurementId: 'G-475P5VSEQJ',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrGmMTg27SbCCza3_-JVlD_TAvWXOHULs',
    appId: '1:912044780067:web:2590f570ee459aaecadf96',
    messagingSenderId: '912044780067',
    projectId: 'meal-app-ngt',
    authDomain: 'meal-app-ngt.firebaseapp.com',
    storageBucket: 'meal-app-ngt.firebasestorage.app',
    measurementId: 'G-78845XPPM8',
  );
}
